CREATE DATABASE IF NOT EXISTS ex1 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS ex2 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS ex3 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS ex4 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON ex1.* TO 'miuser'@'%';
GRANT ALL PRIVILEGES ON ex2.* TO 'miuser'@'%';
GRANT ALL PRIVILEGES ON ex3.* TO 'miuser'@'%';
GRANT ALL PRIVILEGES ON ex4.* TO 'miuser'@'%';
FLUSH PRIVILEGES;